package com.plcoding.cleanarchitecturenoteapp.featue_student.domain.util

data class StandStillDataDTO(
    val l0 : Float,
    val l1 : Float,
    val l2 : Float,
    val l3 : Float,
    val l4 : Float,
    val l5 : Float,
    val l6 : Float,
    val l7 : Float,
    val l8 : Float,
    val l9 : Float,
    val l10 : Float,
    val l11 : Float,
    val l12 : Float,
    val l13 : Float,
    val l14 : Float,
    val l15 : Float,
    val r0 : Float,
    val r1 : Float,
    val r2 : Float,
    val r3 : Float,
    val r4 : Float,
    val r5 : Float,
    val r6 : Float,
    val r7 : Float,
    val r8 : Float,
    val r9 : Float,
    val r10 : Float,
    val r11 : Float,
    val r12 : Float,
    val r13 : Float,
    val r14 : Float,
    val r15 : Float,
    val time_stamp : Long,
)
